complex(concept).
has(concept,components)
defined_by(concept,components).
has(concept,combination).
multiplicity(concept).
has(concept,irregular_contour).
solution(concept,problem).
function_of(concept,problems).
has_history(concept).
junction_of_problems(concepts,coexisting_concepts).
concept(concept).
relates_back_to(concept,other_concepts).
accumulation(concept,its_own_components).
traverses(conceptual_point,its_components).
heterogenesis(concept).
ordering_of(zones_of_neighborhood,its_components).
incorporeal(concept).
is_incarnated_in(concept,bodies).
has(concept,intensive_ordinates).
anenergetic(concept).
speaks(concept,event).
absolute(concept).
relative(concept).
relative_to(concept, its_own_components).
relative_to(concept,other_concepts).
through(infinite,survey).
through(finite,movement).
unites(constructivism,the_relative).
unites(constructivism,the_absolute).
self_referential(concept).
center_of_vibration(concept).
junctions(bridges).
detours(bridges).
movable_bridge(concept).
must_be(planes,constructed.
muste_be(problems,posed).
must_be(concepts,created).
relate_to(new_concepts,problems).
relate_to(new_concepts,our_history).
relate_to(new_concepts,our_becomings).
are_not(concepts,eternal).
contour(concept).
configuration(concept).
constellation(concept).
of(contour,event_to_come).
obvious_knowledge(concept).
creates(philosophy,concepts).
shapes(concept,event).
reshapes(concept,event).
belongs_to(concept,philosophy).
